name: Pokemon CLI - Docker Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'pokemon-cli/**'

permissions:
  contents: read

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Registry
        run: docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io/s4nchez/pokemon-api
      - name: Start Pokemon API server
        run:  docker run -p 8080:8080 -d ghcr.io/s4nchez/pokemon-api:latest
      - name: Make a request
        run: sleep 5 && curl -v http://localhost:8080

