name: Pokemon CLI - Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'pokemon-cli/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build
        run: ./gradlew pokemon-cli:check
      - name: Integration Test (vs latest)
        run: ./gradlew pokemon-cli:integrationTest
        env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: jUnit Tests
          path: 'pokermon-cli/build/test-results/*.xml'
          reporter: java-junit
