name: Pokemon API - Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/pokemon-api-build.yml'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'pokemon-api/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
#      - name: Build
#        run: ./gradlew pokemon-api:check
      - name: Publish Docker Image
        run: |
          ./gradlew jib \
          -Djib.to.image=ghcr.io/s4nchez/pokemon-api:latest \
          -Djib.to.tags=${{ github.sha }} \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
        shell: bash
