name: Pokemon CLI - Pokemon API Integration (specific version)

on:
  repository_dispatch:
    types: [new-version-pokemon-api]

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Integration Tests (vs ${{ github.event.client_payload.docker_label }})
        run: ./gradlew pokemon-cli:integrationTest
        env:
          IMAGE_TAG: ${{ github.event.client_payload.docker_label }}
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: Integration Test (vs ${{ github.event.client_payload.docker_label }})
          report_paths: '**/build/test-results/integrationTest/*.xml'
          detailed_summary: summary

